"""Add file_content column and remove file_path

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add file_content column
    op.add_column('file_versions', sa.Column('file_content', sa.LargeBinary(), nullable=True))

    # Remove file_path column
    op.drop_column('file_versions', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add file_path column back
    op.add_column('file_versions', sa.Column('file_path', sa.VARCHAR(), nullable=False))

    # Remove file_content column
    op.drop_column('file_versions', 'file_content')
    # ### end Alembic commands ###
